### ISSUE TITLE
Signature from Ledger Nano X will be marked as invalid transaction

### ISSUE THREAD

**Issue by BlankerL** [HuobiGroup/huobi-eco-chain#1]
Hello, 

I am a user of Hecochain, and already deposit some HT into my Hecochain address. 

However, when I am sending transactions on my Ledger Nano X to transfer the HT to other addresses, it always says "invalid signature". Such a situation has last for at least 5 days, and my HT is "freezed" in my Hecochain address. 

You can see the picture below, I am sure the signature is signed by the corresponding address. 
![image](https://user-images.githubusercontent.com/24969376/103405321-a4134700-4b91-11eb-9220-7f6a50a5f9d6.png)

I have reported this issue in WeChat, but no one is replying to me. If you do not trust me, please have a try on your own. 

Please help me if possible.

**Comment by MButcho** [comment]
I have same issue on native Crypto Wallet of Brave browser. Other chains are working fine.

**Comment by yonghoban** [comment]
I have same issue. 
How can I transaction confirm?

**Comment by kevinho** [comment]
Some users have found a workaround, and post it in :

https://www.jianshu.com/p/63e392070b20

please check out, and be careful before you make the action!
