### ISSUE TITLE
fail to query balance at given height

### ISSUE THREAD

**Issue by readygo586** [HuobiGroup/huobi-eco-chain#10]
take 0x88888ad1141c2196b75321c6721ed51d18b7a9f6 as example.

//success to query latest balance. latest height = 2471496 
curl -X POST -H ‘content-type:application/json’  --data ‘{“jsonrpc”:“2.0",“method”:“eth_getBalance”,“params”:[“0x88888ad1141c2196b75321c6721ed51d18b7a9f6", “latest”],“id”:1}’  https://http-mainnet.hecochain.com
{“jsonrpc”:“2.0",“id”:1,“result”:“0x69f5712d87103f80”}

//failt to query balance at height=2431283
curl -X POST -H ‘content-type:application/json’  --data ‘{“jsonrpc”:“2.0”,“method”:“eth_getBalance”,“params”:[“0x88888ad1141c2196b75321c6721ed51d18b7a9f6”, “0x251933"],“id”:1}’  https://http-mainnet.hecochain.com
{“jsonrpc”:“2.0”,“id”:1,“error”:{“code”:-32000,“message”:“missing trie node 96d008cb166f3b342760b3d79bd85d8324c1f69c6d881902ddd6ffb8368dc319 (path )“}}

//failt to query balance at height=2471308, latest height = 2471496 
curl -X POST -H ‘content-type:application/json’  --data ‘{“jsonrpc”:“2.0",“method”:“eth_getBalance”,“params”:[“0x88888ad1141c2196b75321c6721ed51d18b7a9f6", “0x25b58c”],“id”:1}’  https://http-mainnet.hecochain.com
{“jsonrpc”:“2.0",“id”:1,“result”:“0x699cb78b804a8480”}

**Comment by wangsai-silence** [comment]
https://http-mainnet.hecochain.com is not in archive mode.
