### ISSUE TITLE
有没有更多的主网节点

### ISSUE THREAD

**Issue by hashpaypie** [HuobiGroup/huobi-eco-chain#13]
官方的只有三个节点同步吗？    ’full‘ 模式 最后面一个月同步的时候特别的慢。两天了还没同步完成

**Comment by tmors** [comment]
能给个可以用的enode吗？ bootnode里面的三个都不能连上

**Comment by wangsai-silence** [comment]
> 能给个可以用的enode吗？ bootnode里面的三个都不能连上

https://docs.hecochain.com/#/mainnet 可以看下这里
