### ISSUE TITLE
make geth   error;

### ISSUE THREAD

**Issue by crow123** [HuobiGroup/huobi-eco-chain#14]
![image](https://user-images.githubusercontent.com/15045264/113084451-944ae380-9210-11eb-81e5-226f84b92ce3.png)
![image](https://user-images.githubusercontent.com/15045264/113084483-a4fb5980-9210-11eb-9a0f-518b5db6bd50.png)

centos8   该怎么解决这个问题？是go的版本不对吗

**Comment by barryz** [comment]
The latest go version will fix this issue. Also, go module supported since go 1.14.
