### ISSUE TITLE
Ht reward

### ISSUE THREAD

**Issue by nelcrypto** [HuobiGroup/huobi-eco-chain#21]
https://scan-testnet.hecochain.com/faucet?error=application_suspended&error_description=Your%20application%20has%20been%20suspended.%20Please%20contact%20support%40github.com.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23application-suspended

**Comment by Nanyan** [comment]
Thanks for your feedback.

It's been fixed, please try again.

And for any issues relates to the test-net faucet, it's welcome to feedback through heco-developer WeChat groups. It will get more timely response.
