### ISSUE TITLE
web3j java连接报错，但是区块又监听，连以太测试网不会出现

### ISSUE THREAD

**Issue by makeaini** [HuobiGroup/huobi-eco-chain#23]
org.web3j.protocol.core.filters.FilterException: Invalid request: filter not found
连以太测试网不会出现

![image](https://user-images.githubusercontent.com/5669878/119945964-a8208500-bfc8-11eb-9783-ce3fdec772e6.png)

**Comment by yyf12** [comment]
hi，我连bsc主网也有同样问题，有什么好的解决方案吗

**Comment by wangsai-silence** [comment]
这个是因为官方rpc的服务是有多个节点的负载均衡的， 每次请求都会被分配到不同的节点上，所以不建议使用filter请求官方rpc，如果有此需求，建议自建节点。
