### ISSUE TITLE
火币生态上要怎么发行自己的代币

### ISSUE THREAD

**Issue by dengmin** [HuobiGroup/huobi-eco-chain#24]
怎么发行自己的代币, 也没有详细的操作文档

**Comment by jc0803kevin** [comment]
@dengmin 这个和erc20 差不多。用小狐狸就可以发，添加一个网络

**Comment by dengmin** [comment]
@jc0803kevin 这个我知道怎么发, 但是要怎么把代币发到mdex上去

**Comment by jc0803kevin** [comment]
> @jc0803kevin 这个我知道怎么发, 但是要怎么把代币发到mdex上去

发完代币，有了合约地址，发到mdex上面 啥意思？
