### ISSUE TITLE
eth_sendRawTransaction send 成功返回txid，偶发出现eth_getTransactionCount  获取from地址pending nonce的时候，值没有增加的情况

### ISSUE THREAD

**Issue by summerxue1992** [HuobiGroup/huobi-eco-chain#28]
怀疑是调节点广播接口返回成功，但是交易没有入内存池。 这个情况有节点方面解决的方案吗？ 配置或者策略也行

**Comment by wangsai-silence** [comment]
只要是广播返回成功，肯定是进入交易池并校验通过的。

**Comment by summerxue1992** [comment]
eth就碰到过类似的情况，很偶尔，但是heco链最近经常碰到，和同一时间广播频率高有关系吧

**Comment by wangsai-silence** [comment]
如果是使用的官方提供的RPC节点，则可能是因为两次请求发送到了不同的节点上，而节点之间的数据还没有完全同步导致的。
