### ISSUE TITLE
geth syncing is hanged

### ISSUE THREAD

**Issue by dbarobin** [HuobiGroup/huobi-eco-chain#36]
#### System information

Geth version: `1.1.1-stable`
OS & Version: Ubuntu 20.04.2 LTS
Server location: AWS us-east
Server type: Amazon EC2 M6g instances are powered by Arm-based AWS Graviton2 processors. 
Commit hash : b5a6d1aec0be3021e2eb98d7a79097581d2afa07

#### Expected behaviour

> geth is full sync the latest blocks of heco mainnet.

#### Actual behaviour

geth syncing is hanged and the following error is reported.

> INFO [07-27|08:02:50.182] metric                                   method=broadcastBlock peer=008f72fd83d9d072 hash=0x35addb623f921e03da96122aead7f631fa5406eb8e2408d13bb544f7161fc898 number=6826402 fullBlock=false

#### Steps to reproduce the behaviour

1. Install golang and build geth.
2. Syncing blocks.

``` bash
#!/usr/bin/env bash
nohup /data/heco/geth \--config /data/heco/config.toml  \
--logpath /data/heco/logs \--verbosity 3  >> /data/heco/logs/systemd_chain_console.out 2>&1 &
```

3. Syncing the latest blocks and hanged.

**Comment by Nanyan** [comment]
Thanks for your reporting, can you provide more details?

Is there any more logs? The log you listed `INFO [07-27|08:02:50.182] metric method` is not an error log.

And is there any logs in the file `systemd_chain_console.out` ?

**Comment by dbarobin** [comment]
Thanks for your reply.

`systemd_chain_console.out` does not have any content.

``` bash
-rw-rw-r-- 1 ubuntu ubuntu        0 Jul 26 07:15 systemd_chain_console.out
```

**Comment by Nanyan** [comment]
So currently you have not showing any error messages. 
What is the head block number? 
Does your `geth` still running?
Are there any logs after the log `INFO [07-27|08:02:50.182] metric method ...` ?

The block `6826402` which showed in your log is mined at `2021-07-27 08:02:50 UTC`, so I think your node may have already catching up the latest block of the heco-mainnet.

**Comment by dbarobin** [comment]
1. I can't find the head block because the `eth.syncing` return the falase.
2. Sure, my `geth` is runing, and I can see the new logs in the chain.log.
3. No.
4. Because I `kill -9` the geth and the syncing is working. But when syncing near the latest block, the geth hangd.

**Comment by Nanyan** [comment]
`eth.syncing` returns `false` means your node already catching up with the latest block of the network, there are no any more history blocks need to sync.

You can type `eth.blockNumber` to see the HEAD block number of your node.

**Comment by dbarobin** [comment]
I'm sorry, I'm not familiar with geth.

Another question, when I apply the heco node, and the page say "The address cannot be pledged.". But my heco address have 5000 HT more.

Can you explain why it happened? And how to solve this issue? Thanks.
