### ISSUE TITLE
JSON RPC documentation

### ISSUE THREAD

**Issue by paulvi** [HuobiGroup/huobi-eco-chain#40]
Apart from standard JSON RPC
@ethereum `geth` has implemented real/time pub/sub https://geth.ethereum.org/docs/rpc/pubsub

I wonder how to compare `geth` version with HECO node,
and if there is documentation similar to  https://geth.ethereum.org/docs

**Comment by wangsai-silence** [comment]
HECO is forked from go-ethereum 1.9.23 and supprort most api from go-ethereum.

**Comment by paulvi** [comment]
So if to get snapshot of https://geth.ethereum.org/docs/rpc/pubsub docs for time of 1.9.23
Than it will be exact.

How about newer API and changes?
Do you selectively port some geth code?

Or maybe you pull most of it ?

I think for every HECO node version, there should be listed related geth version, so that things are clear.
