### ISSUE TITLE
[deployment] Different version in mainnet and testnet

### ISSUE THREAD

**Issue by paulvi** [HuobiGroup/huobi-eco-chain#41]
I don't if that is important, but there are Different version in mainnet and testnet: 1.1.0 vs 1.1.3

testnet
Geth/v1.1.0-unstable-e4513621-20210629/linux-amd64/go1.13.4
mainnet
Geth/v1.1.3-stable-67a191de/linux-amd64/go1.13.4

I think testnet should be the same or newer than mainnet, not vice versa.

**Comment by wangsai-silence** [comment]
> I don't if that is important, but there are Different version in mainnet and testnet: 1.1.0 vs 1.1.3
> 
> testnet
> Geth/v1.1.0-unstable-e4513621-20210629/linux-amd64/go1.13.4
> mainnet
> Geth/v1.1.3-stable-67a191de/linux-amd64/go1.13.4
> 
> I think testnet should be the same or newer than mainnet, not vice versa.

Thanks for your advice. We have upgraded all testnet nodes today.
