### ISSUE TITLE
It will loss a large number of blocks when I reboot the geth

### ISSUE THREAD

**Issue by ptr66** [HuobiGroup/huobi-eco-chain#42]
Geth version: 1.1.1-stable
OS & Version: Linux

Hi,  It will loss a large number of blocks when I reboot the geth. Like this（I catch the state of syncing after reboot）：

> eth.syncing
{
  currentBlock: 7881263,
  highestBlock: 7970698,
  knownStates: 190833495,
  pulledStates: 190833495,
  startingBlock: 7970681
}

I think the 'startingBlock' is right, it is the block number where the moment I kill the geth process, but the 'currentBlock' is wrong, and I find the problem also exist in old geth version. How can I repair this problem？ Thank you！

**Comment by wangsai-silence** [comment]
Do not use kill -9. Use kill -15

**Comment by ptr66** [comment]
> Do not use kill -9. Use kill -15

That's what I used before, but the problem remains.
