### ISSUE TITLE
upgrade the node to 1.2.0-stable , but has a error, Fatal: /data/blockdata/heco/conf/config.toml, line 3: field 'DiscoveryURLs' is not defined in ethconfig.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth/ethconfig#Config for available fields,

### ISSUE THREAD

**Issue by malingzhao** [HuobiGroup/huobi-eco-chain#43]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Nanyan** [comment]
you should just remove the field `DiscoveryURLs`

**Comment by malingzhao** [comment]
Thank you very much， The problem has been resolved
