### ISSUE TITLE
geth not startup

### ISSUE THREAD

**Issue by SundyHu** [HuobiGroup/huobi-eco-chain#44]
INFO [09-18|10:16:56.182] Starting Geth on testnet... 
Fatal: /data/heco/config.toml, line 3: field 'DiscoveryURLs' is not defined in ethconfig.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth/ethconfig#Config for available fields

**Comment by PatHoo** [comment]
`make geth` under CentOS 8.3, and then scp it to Ubuntu 20.04, works for me.

**Comment by Nanyan** [comment]
Just remove the `DiscoveryURLs` in your config.toml file
