### ISSUE TITLE
官方主网节点RPC支不支持personal_*相关方法？

### ISSUE THREAD

**Issue by desslee** [HuobiGroup/huobi-eco-chain#46]
官方提供的以下节点， 使用web3j请求创建账户相关接口提示方法不存在或不可用,
请问是不支持必须自己部署节点还是我的请求方式有误？
```
Admin admin = Admin.build(new HttpService("https://http-mainnet-node.huobichain.com"));
NewAccountIdentifier newAccountIdentifier = admin.personalNewAccount("password").send();
```

````
the method personal_newAccount does not exist/is not available
the method personal_unlockAccount does not exist/is not available
```

官方节点
https://http-mainnet-node.huobichain.com
https://http-mainnet-node.defibox.com

**Comment by wangsai-silence** [comment]
> 官方提供的以下节点， 使用web3j请求创建账户相关接口提示方法不存在或不可用,
> 请问是不支持必须自己部署节点还是我的请求方式有误？
> 
> ```
> Admin admin = Admin.build(new HttpService("https://http-mainnet-node.huobichain.com"));
> NewAccountIdentifier newAccountIdentifier = admin.personalNewAccount("password").send();
> ```
> 
> ```
> the method personal_newAccount does not exist/is not available
> the method personal_unlockAccount does not exist/is not available
> ```
> 
> 官方节点
> https://http-mainnet-node.huobichain.com
> https://http-mainnet-node.defibox.com
> ```

官方节点不支持此类操作，也暂时没有任何场景需要添加这类支持。如果有需要，可以自建节点来实现。
