### ISSUE TITLE
get 'can't load package: package .: no Go files in /' when 'make geth-linux-amd64'

### ISSUE THREAD

**Issue by kilinger** [HuobiGroup/huobi-eco-chain#5]
Checking for required docker image karalabe/xgo-latest... found.
Cross compiling ....
Building locally ....
Compiling for linux/amd64...
can't load package: package .: no Go files in /
2021/02/09 20:03:35 Failed to cross compile package: exit status 1.
util.go:45: exit status 1
exit status 1
make: *** [Makefile:74：geth-linux-amd64] error 1

**Comment by Nanyan** [comment]
@kilinger It's mainly because the `xgo` didn't support package that did not under the `GOPATH`. See the relative issue [go-ethereum issues 21309](https://github.com/ethereum/go-ethereum/issues/21309).

My recommendation is to use [xgo2](https://github.com/youchainhq/xgo2).
