### ISSUE TITLE
About contract creation

### ISSUE THREAD

**Issue by LuckyLQD** [HuobiGroup/huobi-eco-chain#52]
How to solve this problem: when I deploy a contract by REMIX, it shows the error:
creation of Storage errored: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"transaction underpriced"}}}'
When I use ethers, the error occurs too. Could you please tell me how to solve it? How to set the gas price?

**Comment by Nanyan** [comment]
On the first window of a transaction in Metamask, you will  see a button " EDIT ", click it and then click "Edit suggested gas fee" , then you can edit the Max priority fee and the Max fee, both should ≥ 2.25 GWEI currently.

**Comment by LuckyLQD** [comment]
Thanks Nanyan. It is ok now.
