### ISSUE TITLE
How to use debug_trace?

### ISSUE THREAD

**Issue by CaiJiJi** [HuobiGroup/huobi-eco-chain#53]
V1.2.0 support debug tx?
```
now it will be ok to debug_trace those blocks containing sys-txs (transactions initiated inside the Congress engine).
```
how to use it?

**Comment by Nanyan** [comment]
No special for usage. 
Please refer to [the geth docs for debug namespace](https://geth.ethereum.org/docs/rpc/ns-debug) for those `debug_trace##` funcs (e.g. `debug_traceBlockByNumber`) or `debug_standardTrace##` funcs.
